services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  queue:
    build: .
    command: php artisan queue:work
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  vendor:
